codecov:
  require_ci_to_pass: yes

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        threshold: 5
    patch: false
CODECOV_TOKEN="1204ebb9-e8d2-4787-a82b-6df948b7c593
